global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
      
  - job_name: 'alerting-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']