global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
      
  - job_name: 'alerting-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
      
  - job_name: 'information-service'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'sensor-service'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]