# prometheus.yml
global:
  scrape_interval: 1s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: 'information-service'
    static_configs:
      - targets: ['host.docker.internal:8082']